### ISSUE TITLE
Commands fail for some reason namespace required

### ISSUE THREAD

**Issue by jangor** [eciggaar/jfall2020-workshop#1]
Following the workshop on thursday i have some issues which get resolved by adding namespace.

Following the steps in the instructions openshift/8-Pipelines.md i came accross the following problems:

The first seems related to the namespace:
```
$ tkn pipeline list 
No Pipelines found
$ tkn pipeline -n jfall-workshop list
NAME...
jfall-pipeline ...

```
Another one i don't seem to get right:
```
kn service describe knative-jfall-service
services.serving.knative.dev "knative-jfall-service" not found
```

Perhaps something to improve in the instructions perhaps something particular in my environment/configuration... 
Note: I do have the "knative-jfall-service"
![knative-jfall-service](https://user-images.githubusercontent.com/4834812/98298453-4cec5e00-1fb6-11eb-81c8-225650711367.PNG)
 in the Openshift Console.

I was able to successfully complete the workshop including the traffic management.
Thanks again for the workshop!

**Comment by eciggaar** [comment]
Thnx for bringing this to our attention and for joining our session yesterday! Hope you enjoyed it!! 

I updated the instructions for this step to explicitly change to the `jfall-workshop` project. The YAML with resource definitions all contain the namespace, except for the `pipeline-resources.yml`. This has now been changed as well.
